language: node_js
os: linux
node_js:
  - "12"

cache:
  directories:
    - ./node_modules

install:
  - npm install
script:
  - npm run build
deploy:
  strategy: git
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/my-dream-app
  keep_history: true
  on:
    branch: master
